# Generated by Django 3.1.2 on 2020-10-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201028_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='programming_language',
            field=models.CharField(choices=[('PY', 'Python'), ('JA', 'Java'), ('JS', 'JavaScript'), ('C/C++', 'C/C++'), ('RB', 'Ruby'), ('GO', 'Go')], default='Python', max_length=30),
        ),
    ]
