# Generated by Django 3.1.2 on 2020-11-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='invitee_email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
