# Generated by Django 3.1.2 on 2020-11-11 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mock_site', '0002_session_invitee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='video_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
